Mikhail Paulyshka - 0
rubizza-survival-camp/winter-2018 pull request #34
Opened 2018-12-09 20:40 UTC by Mixaill

## Name
Mikhail Paulyshka

## Homework#
0

## Comment
Level 1, 2 and 3

2018-12-10 05:57 UTC, RGBD requested changes

2018-12-10 05:57 UTC, RGBD commented on Mikhail Paulyshka/0/run.rb
> +  prices_found.each do |k, v|
есть методы min_by, max_by

2018-12-10 10:21 UTC, Mixaill commented on Mikhail Paulyshka/0/data_downloader.rb
> +    Dir.entries(DIRECTORY).reject { |f| File.directory? f }.map { |f| DIRECTORY + f }
fixed

2018-12-10 10:21 UTC, Mixaill commented on Mikhail Paulyshka/0/data_downloader.rb
> +class DataDownloader
fixed

2018-12-10 10:21 UTC, Mixaill commented on Mikhail Paulyshka/0/run.rb
> +    rescue RuntimeError
fixed

2018-12-10 10:22 UTC, Mixaill commented on Mikhail Paulyshka/0/run.rb
> +    month = regex_result[0][1]
fixed for consistency. 
I have to convert year to integer because I use it later as criteria for BYR->BYN conversion.

2018-12-10 10:22 UTC, Mixaill commented on Mikhail Paulyshka/0/run.rb
> +  prices_found.each do |k, v|
fixed

2018-12-10 10:37 UTC, Mixaill commented
@RGBD First bunch of issues was fixed, waiting for further feedback :)

2018-12-10 11:35 UTC, RGBD commented
@Mixaill, looks good to me, fix remaining rubocop issues, please.

2018-12-18 07:02 UTC, RGBD commented
@Mixaill, any updates?

2023-05-01 13:19 UTC, closed without merging