Alena Zubritskaya - 0
rubizza-survival-camp/winter-2018 pull request #36
Opened 2018-12-09 21:01 UTC by superpuper777

## Name
Alena Zubritskaya

## Homework#
0

## Comment
Level 1

2018-12-11 06:51 UTC, RGBD requested changes
Fix rubocop issues.

2018-12-11 06:51 UTC, RGBD commented on Alena Zubritskaya/0/Gemfile
> +gem 'rubyXL'
add newline

2018-12-11 06:51 UTC, RGBD commented on Alena Zubritskaya/0/level1.rb
> +    price = row.cells[14]&.value || "unknown"
make 14 a constant

2018-12-11 06:51 UTC, RGBD commented on Alena Zubritskaya/0/level1.rb
> +    if row.cells[0].value.include?(ans)
if item_name ...

2018-12-11 06:51 UTC, RGBD commented on Alena Zubritskaya/0/level1.rb
> +  if
remove newline after if

2018-12-15 22:17 UTC, RGBD commented
Достаточно вывести два похожих товара по цене.
```
% ruby level3.rb
What price are you looking for?
мясо лося
Traceback (most recent call last):
        8: from level3.rb:14:in `<main>'
        7: from /home/oleg/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/find.rb:43:in `find'
        6: from /home/oleg/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/find.rb:43:in `each'
        5: from /home/oleg/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/find.rb:48:in `block in find'
        4: from /home/oleg/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/find.rb:48:in `catch'
        3: from /home/oleg/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
        2: from level3.rb:18:in `block in <main>'
        1: from level3.rb:18:in `each'
level3.rb:39:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
```
много повторений в выводе
```
Й ЭЛЕКТРИЧЕСКИЙ is 168.46 BYN за сентябрь 2016 года**
For similar price you also can afford:
Lowest was on за март 2017 года** at price 142.97 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 169.29 BYN за октябрь 2016 года**
For similar price you also can afford:
Lowest was on за март 2017 года** at price 142.97 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 142.46 BYN за сентябрь 2015 года**
For similar price you also can afford:
Lowest was on  at price 142.46 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 192.6011 BYN in Minsk these days
For similar price you also can afford:
Lowest was on  at price 142.46 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 162.97 BYN за июнь 2016 года**
For similar price you also can afford:
Lowest was on  at price 142.46 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 174.06 BYN за июль 2016 года**
For similar price you also can afford:
Lowest was on  at price 142.46 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 141.29 BYN за октябрь 2015 года**
For similar price you also can afford:
Lowest was on  at price 141.29 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 150.33 BYN за декабрь 2015 года**
For similar price you also can afford:
Lowest was on  at price 141.29 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 150.16 BYN за январь 2016 года**
For similar price you also can afford:
Lowest was on  at price 141.29 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 159.46 BYN за апрель 2016 года**
For similar price you also can afford:
Lowest was on  at price 141.29 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 181.7 BYN за декабрь 2016 года**
For similar price you also can afford:
Lowest was on  at price 141.29 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
ПЫЛЕСОС НАПОЛЬНЫЙ ЭЛЕКТРИЧЕСКИЙ is 168.08 BYN за май 2016 года**
For similar price you also can afford:
Lowest was on  at price 141.29 BYN
Highest was on за сентябрь  2018 года** at price 196.72 BYN
37 files were found
%         
```

2018-12-23 08:02 UTC, superpuper777 commented
Tell me please how fix this error
Error: We detected some problems with your configuration file.

2021-04-01 23:59 UTC, closed without merging