Add homework-1
rubizza-survival-camp/winter-2018 pull request #50
Opened 2019-01-31 14:55 UTC by superpuper777

## Name
Alena Zubritskaya

## Homework#
1
## Comment
Level 1.

## Checklist
- [ ] I have read homework assignment fully
- [ ] I have implemented homework assignment fully
- [ ] My pull request is named "#{name} #{surname} - #{homework_number}"
- [ ] My code is located under "#{name} #{surname}/#{homework_number}"
- [ ] It executes correctly
- [ ] It doesn't crash, freeze, kill everyone on unexpected input
- [ ] Credentials are NOT hardcoded
- [ ] Large files and credentials added to .gitignore INSIDE homework dir
- [ ] It can be tested in under 10 minutes (download part + parse + execute)
- [ ] Gemfile added, it runs under bundle exec without error

2019-02-05 20:23 UTC, RGBD requested changes

2019-02-05 20:23 UTC, RGBD commented on Alena Zubritskaya/1/lib/wordplay_fevr_bot.rb
> +    @token = '603660924:AAFQSiTlEJNAh1zCt4MgwAkCZt1rprEebjc'
Credentials should not be hardcoded

2019-02-05 20:23 UTC, RGBD commented on Alena Zubritskaya/1/lib/database.rb
> +    (0...@parser.length).each do |i|
https://ruby-doc.org/core-2.2.0/Integer.html#method-i-times

2019-02-05 20:23 UTC, RGBD commented on Alena Zubritskaya/1/lib/database.rb
> +    i = rand(0...@parser.length)
rand(@parser.length)

2019-03-02 10:12 UTC, superpuper777 commented
What's mean invalid?

2021-04-02 00:00 UTC, closed without merging